### ISSUE TITLE
Ability to use the older style of inline code?

### ISSUE THREAD

**Issue by ibhagwan** [previm/previm#179]
This commit https://github.com/previm/previm/commit/108e3eceb02430d6ace65f1fcc18d7f4b64204c3 changes the style of inline code.

Prior to the commit:
![image](https://user-images.githubusercontent.com/59988195/178373299-466a083a-dab6-4928-a046-9e6be7157338.png)

After the commit the highlights of the code highlighting changed and there's also a bit of padding inside the code box with a slightly different color around it:
![image](https://user-images.githubusercontent.com/59988195/178373377-00b6152d-8ce4-4504-8445-268d544d5a48.png)

**Comment by ibhagwan** [comment]
Actually I was able to change the background and forground colors using the custom `css` but I'm still unable to overwrite the `highlights.js` syntax theme.

Relevant part from the `css`:
```css
pre code.hljs {
  color: #ADBAC7;
  background-color: #3c434d;
}

/* .hljs-comment{color:#7fdbca} */
.hljs-string,
.hljs-section,
.hljs-selector-class,
.hljs-template-variable,
.hljs-deletion {
  color: #fff;
}
```
If I change `hljs-string` directly inside `preview/_/css/lib/highlight.css` it works and I get the right color but for some reason it doesn't apply it when inside my custom css, the result is correct background/foreground but no syntax theme update:
![image](https://user-images.githubusercontent.com/59988195/178405812-2da1f6ca-6fa8-4c61-b721-78d1f03c1fae.png)
